version: '3'

tasks:
  deps:
    desc: Install and verify project dependencies
    cmds:
      - make deps

  fmt:
    desc: Format code according to project standards
    cmds:
      - make fmt

  lint:
    desc: Run lint checks without auto-fixing
    cmds:
      - make lint-check

  test:
    desc: Run Go test suite with coverage
    cmds:
      - make test

  verify:
    desc: Run full verification pipeline (fmt, lint, vet, test)
    cmds:
      - make verify
