apiVersion: v1
kind: ConfigMap
metadata:
  name: atest-ai-plugin-config
  namespace: atest-system
  labels:
    app.kubernetes.io/name: atest-ext-ai
    app.kubernetes.io/component: plugin
data:
  config.yaml: |
    # AI Plugin Configuration
    ai:
      provider: local
      ollama_endpoint: http://ollama-service:11434
      model: codellama
      confidence_threshold: 0.7
      enable_sql_execution: true
      supported_databases:
        - mysql
        - postgresql
        - sqlite
      max_concurrent_requests: 10
      request_timeout: 30s
      cache_ttl: 3600s

    plugin:
      socket_path: /tmp/atest-store-ai.sock
      health_check_interval: 30s
      log_level: info
      metrics_enabled: true
      metrics_port: 9090

    security:
      enable_audit_log: true
      max_request_size: 10MB
      rate_limit:
        enabled: true
        requests_per_minute: 60

    databases:
      mysql:
        max_connections: 10
        connection_timeout: 5s
      postgresql:
        max_connections: 10
        connection_timeout: 5s
      sqlite:
        max_connections: 1
        connection_timeout: 5s

    logging:
      level: info
      format: json
      output: stdout
      audit:
        enabled: true
        file: /var/log/atest-ai/audit.log

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-config
  namespace: atest-system
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: ai-service
data:
  OLLAMA_ORIGINS: "*"
  OLLAMA_HOST: "0.0.0.0"
  OLLAMA_PORT: "11434"