apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: atest-system
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: ai-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
  # Optional: specify selector for custom PV
  # selector:
  #   matchLabels:
  #     app: ollama

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atest-logs-pvc
  namespace: atest-system
  labels:
    app.kubernetes.io/name: atest-ext-ai
    app.kubernetes.io/component: plugin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  # For shared logging across plugin instances