apiVersion: v1
kind: ServiceAccount
metadata:
  name: atest-ai-plugin
  namespace: atest-system
  labels:
    app.kubernetes.io/name: atest-ext-ai
    app.kubernetes.io/component: plugin
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: atest-ai-plugin
  namespace: atest-system
  labels:
    app.kubernetes.io/name: atest-ext-ai
    app.kubernetes.io/component: plugin
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: atest-ai-plugin
  namespace: atest-system
  labels:
    app.kubernetes.io/name: atest-ext-ai
    app.kubernetes.io/component: plugin
subjects:
- kind: ServiceAccount
  name: atest-ai-plugin
  namespace: atest-system
roleRef:
  kind: Role
  name: atest-ai-plugin
  apiGroup: rbac.authorization.k8s.io

---
# ClusterRole for cross-namespace access if needed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atest-ai-plugin-cluster
  labels:
    app.kubernetes.io/name: atest-ext-ai
    app.kubernetes.io/component: plugin
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atest-ai-plugin-cluster
  labels:
    app.kubernetes.io/name: atest-ext-ai
    app.kubernetes.io/component: plugin
subjects:
- kind: ServiceAccount
  name: atest-ai-plugin
  namespace: atest-system
roleRef:
  kind: ClusterRole
  name: atest-ai-plugin-cluster
  apiGroup: rbac.authorization.k8s.io