# atest-ext-ai Default Configuration
# This file contains the default configuration for the AI Testing Extension

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  timeout: "30s"
  max_connections: 100
  socket_path: "/tmp/atest-ext-ai.sock"
  read_timeout: "15s"
  write_timeout: "15s"

# Plugin Configuration
plugin:
  name: "atest-ext-ai"
  version: "1.0.0"
  debug: false
  log_level: "info"
  environment: "development"
  metadata:
    author: "api-testing-team"
    description: "AI-powered testing extension"

# AI Service Configuration
ai:
  default_service: "ollama"
  timeout: "60s"
  fallback_order:
    - "ollama"
    - "openai"
    - "claude"

  # Rate limiting configuration
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
    window_size: "1m"

  # Circuit breaker configuration
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    success_threshold: 3
    timeout: "30s"
    reset_timeout: "60s"

  # Retry configuration
  retry:
    enabled: true
    max_attempts: 3
    initial_delay: "1s"
    max_delay: "30s"
    multiplier: 2.0
    jitter: true

  # Cache configuration
  cache:
    enabled: true
    ttl: "1h"
    max_size: 1000
    provider: "memory"

  # Security configuration
  security:
    encrypt_credentials: false
    allowed_hosts:
      - "localhost"
      - "127.0.0.1"
    tls_enabled: false

  # AI Service Definitions
  services:
    ollama:
      enabled: true
      provider: "ollama"
      endpoint: "http://localhost:11434"
      model: "codellama"
      max_tokens: 4096
      temperature: 0.7
      top_p: 0.9
      priority: 1
      timeout: "60s"
      models:
        - "codellama"
        - "llama2"
        - "mistral"
      headers:
        Content-Type: "application/json"

    openai:
      enabled: false
      provider: "openai"
      # api_key: "your-openai-api-key-here"
      model: "gpt-4"
      max_tokens: 4096
      temperature: 0.7
      top_p: 0.9
      priority: 2
      timeout: "60s"
      headers:
        Content-Type: "application/json"

    claude:
      enabled: false
      provider: "claude"
      # api_key: "your-claude-api-key-here"
      model: "claude-3-sonnet"
      max_tokens: 4096
      temperature: 0.7
      top_p: 0.9
      priority: 3
      timeout: "60s"
      headers:
        Content-Type: "application/json"

# Database Configuration (Optional)
database:
  enabled: false
  driver: "sqlite"
  dsn: "file:atest-ext-ai.db?cache=shared&mode=rwc"
  max_connections: 10
  max_idle: 5
  max_lifetime: "1h"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

  # File logging configuration (when output is "file")
  file:
    path: "/var/log/atest-ext-ai.log"
    max_size: "100MB"
    max_backups: 3
    max_age: 28
    compress: true

  # Log rotation configuration
  rotation:
    enabled: true
    size: "100MB"
    count: 5
    age: "30d"
    compress: true

  # Log filters
  filters:
    - name: "sensitive_data"
      level: "warn"
      pattern: "api_key|password|secret"
      fields:
        action: "redact"