# Production configuration for atest-ext-ai plugin
# Minimal configuration with environment variables for sensitive data

server:
  host: "0.0.0.0"
  port: 8080
  timeout: "30s"
  max_connections: 1000
  socket_path: "/var/run/atest-ext-ai.sock"
  read_timeout: "15s"
  write_timeout: "15s"

plugin:
  name: "atest-ext-ai"
  version: "1.0.0"
  debug: false
  log_level: "info"
  environment: "production"

ai:
  default_service: "openai"
  fallback_order: ["openai", "claude", "ollama"]
  timeout: "30s"

  services:
    openai:
      enabled: true
      provider: "openai"
      # Use environment variables for API keys in production
      # Set OPENAI_API_KEY environment variable
      model: "gpt-3.5-turbo"
      max_tokens: 4096
      temperature: 0.1  # Lower temperature for more consistent results
      priority: 1
      timeout: "30s"

    claude:
      enabled: true
      provider: "claude"
      # Set ANTHROPIC_API_KEY environment variable
      model: "claude-3-sonnet-20240229"
      max_tokens: 4096
      temperature: 0.1
      priority: 2
      timeout: "45s"

    ollama:
      enabled: false  # Disabled in production by default
      provider: "ollama"
      # Set OLLAMA_BASE_URL environment variable if using external Ollama
      model: "llama2"
      max_tokens: 4096
      temperature: 0.1
      priority: 3
      timeout: "60s"

  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
    window_size: "1m"

  circuit_breaker:
    enabled: true
    failure_threshold: 3
    success_threshold: 2
    timeout: "30s"
    reset_timeout: "60s"

  retry:
    enabled: true
    max_attempts: 2
    initial_delay: "100ms"
    max_delay: "2s"
    multiplier: 2.0
    jitter: true

  cache:
    enabled: true
    ttl: "30m"
    max_size: 10000
    provider: "memory"

  security:
    encrypt_credentials: true
    allowed_hosts:
      - "api.openai.com"
      - "api.anthropic.com"
    tls_enabled: true

database:
  enabled: false

logging:
  level: "warn"
  format: "json"
  output: "file"
  file:
    path: "/var/log/atest-ext-ai.log"
    max_size: "100MB"
    max_backups: 5
    max_age: 30
    compress: true
  rotation:
    enabled: true
    size: "100MB"
    count: 10
    age: "7d"
    compress: true