# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_extension_pb2 as ai__extension__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_extension_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIExtensionStub(object):
    """AIExtension service provides AI-powered capabilities for atest.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSQLFromNaturalLanguage = channel.unary_unary(
                '/aiextension.AIExtension/GenerateSQLFromNaturalLanguage',
                request_serializer=ai__extension__pb2.GenerateSQLRequest.SerializeToString,
                response_deserializer=ai__extension__pb2.GenerateSQLResponse.FromString,
                _registered_method=True)


class AIExtensionServicer(object):
    """AIExtension service provides AI-powered capabilities for atest.
    """

    def GenerateSQLFromNaturalLanguage(self, request, context):
        """Translates a natural language query into an SQL query, providing
        context and explanations for better accuracy and user trust.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIExtensionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSQLFromNaturalLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSQLFromNaturalLanguage,
                    request_deserializer=ai__extension__pb2.GenerateSQLRequest.FromString,
                    response_serializer=ai__extension__pb2.GenerateSQLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiextension.AIExtension', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiextension.AIExtension', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIExtension(object):
    """AIExtension service provides AI-powered capabilities for atest.
    """

    @staticmethod
    def GenerateSQLFromNaturalLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiextension.AIExtension/GenerateSQLFromNaturalLanguage',
            ai__extension__pb2.GenerateSQLRequest.SerializeToString,
            ai__extension__pb2.GenerateSQLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
